import { SplashScreen, LoginScreen, RegisterScreen, RegisterTokenScreen, ForgotPasswordScreen, ResetPasswordScreen, HelpScreen, ProfileScreen } from './general';
import {
    CreateAccountScreen,
    EcareHomeScreen,
    BuyGigPackScreen,
    UsageScreen,
    RecordScreen,
    PaymentReportScreen,
    ExtraQoutaScreen,
    InternetReportScreen,
    MyServicesScreen,
    CompleteInfoScreen,
    IPGuideScreen,
    PlanScreen,
    ReservationBankScreen,
    RegisteredTicketScreen,
    EditHistoryScreen,
    GiftScreen,
    EditServiceScreen,
    PaymentResultScreen
} from './ecare';

export {
    SplashScreen,
    LoginScreen,
    RegisterScreen,
    RegisterTokenScreen,
    ForgotPasswordScreen,
    ResetPasswordScreen,
    HelpScreen,
    ProfileScreen,
    CreateAccountScreen,
    EcareHomeScreen,
    BuyGigPackScreen,
    UsageScreen,
    RecordScreen,
    PaymentReportScreen,
    ExtraQoutaScreen,
    InternetReportScreen,
    MyServicesScreen,
    CompleteInfoScreen,
    IPGuideScreen,
    PlanScreen,
    ReservationBankScreen,
    RegisteredTicketScreen,
    EditHistoryScreen,
    GiftScreen,
    EditServiceScreen,
    PaymentResultScreen
};